const Array = [
    { id:"1",
      name :"GokulRaj",
      age:30,
      email :"gokulrajnan92@gmail.com"},
    { id:"2",
      name:"Mohanraj",
      age:35,
      email :"mohan@gmail.com"},
      { id:"3",
        name:"Suresh",
        age:45,
        email:"suresh@gmail.com"},
        { id:"4",
        name:"Vijay",
        age:48,
        email:"vijay@gmail.com"},
        { id:"5",
        name:"Ajith",
        age:50,
        email:"ajith@gmail.com"},
        { id:"6",
        name:"Vikram",
        age:55,
        email:"vikram@gmail.com"},
        { id:"7",
        name:"surya",
        age:45,
        email:"surya@gmail.com"},
        { id:"8",
        name:"karthi",
        age:42,
        email:"karthi@gmail.com"},
       { id:"9",
        name:"simbu",
        age:40,
        email:"simbu@gmail.com"},
        { id:"10",
        name:"Dhanush",
        age:39,
        email:"dhanush@gmail.com"},


]
export default Array;